import React, { createContext, useReducer, useEffect } from 'react';
import { exercises } from './data/exercises';
import { getLevelForXP } from './data/levels';
import { isSocialBackendConfigured, syncSocialProfile } from './services/socialService';
import {
  generateProgram,
  adaptProgram,
  getExerciseById,
  getSubstitute,
  computeTarget,
  updateFormProfile,
  getAdaptation,
  getPrescription,
  buildCustomProgram,
  updateEstimated1RM,
} from './services/programEngine';

/**
 * FormForged App State Management
 * Handles: user profile, program, workout sessions, form profile,
 * XP/levels/streaks, settings, onboarding flow.
 */

const STORAGE_KEY = 'formforged_state';

function createReferralCode() {
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let out = 'FF-';
  for (let i = 0; i < 6; i += 1) {
    out += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return out;
}

function normalizeCode(code) {
  return (code || '').trim().toUpperCase();
}

function estimateLeaderboardRank(totalReps = 0) {
  if (totalReps >= 12000) return 1;
  if (totalReps >= 9000) return 2;
  if (totalReps >= 7000) return 3;
  if (totalReps >= 5000) return 5;
  if (totalReps >= 3000) return 9;
  if (totalReps >= 1500) return 15;
  return 25;
}

/** Consecutive-day streak ending today, based on dailyHistory. */
function computeStreak(dailyHistory = {}) {
  let streak = 0;
  const day = new Date();
  for (;;) {
    const key = day.toISOString().split('T')[0];
    const entry = dailyHistory[key];
    if (entry && entry.sessions > 0) {
      streak += 1;
      day.setDate(day.getDate() - 1);
    } else {
      break;
    }
  }
  return streak;
}

const initialState = {
  // Onboarding
  onboardingComplete: false,
  disclaimerAccepted: false,

  // User profile
  gender: 'male',
  activityLevel: 'moderate',
  userProfile: {
    goal: 'muscle',            // strength | muscle | general
    experience: 'intermediate',// beginner | intermediate | advanced
    daysPerWeek: 3,
    progressionModel: 'form-gated', // form-gated | linear | undulating | autoregulated
  },
  userEquipment: [],
  showEquipmentSetup: false,

  // Program + form data (the heart of FormForged)
  program: null,       // generated by programEngine
  nextDayIndex: 0,     // which program day is up next
  formProfile: {},     // { [exerciseId]: { scores, avg, sessions } }
  oneRMs: {},          // { [exerciseId]: { manual: lb|null, estimated: lb|null } }
  showProgramBuilder: false,

  // Gamification
  xp: 0,
  streak: 0,
  totalReps: 0,
  sessionsCompleted: 0,
  leaderboardRank: 25,
  dailyHistory: {},
  exerciseBests: {},
  socialProfile: {
    displayName: 'You',
    referralCode: createReferralCode(),
    referredBy: null,
    friends: [],
  },

  // Current workout session (not persisted)
  workout: null, // { dayIndex, dayName, focus, items: [{exerciseId, sets, results: []}], itemIndex }
  currentExercise: null,
  currentTarget: null,
  repsCompleted: 0,
  isExercising: false,
  manualLogOverride: false, // per-workout "log manually" choice
  formStatus: { level: 'green', message: 'Ready to go' },

  // Post-set summary
  lastSet: null, // { exercise, setNumber, totalSets, cleanReps, flaggedReps, formScore, personalBest, topNote, adaptation, nextAction }
  showLevelUp: false,
  showSummary: false,
  showCamera: false,
  showHowTo: false,
  showLegal: null,

  // Settings
  settings: {
    audioEnabled: true,
    vibrationEnabled: true,
    notificationsEnabled: true,
    dailyReminder: false,
    camera: 'Front',
    units: 'lb', // lb | kg
    formCheckEnabled: true, // false = manual set logging, no camera
  },
};

function loadState() {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      return {
        ...initialState,
        ...parsed,
        userProfile: { ...initialState.userProfile, ...(parsed.userProfile || {}) },
        settings: { ...initialState.settings, ...(parsed.settings || {}) },
        socialProfile: {
          ...initialState.socialProfile,
          ...(parsed.socialProfile || {}),
          referralCode: parsed?.socialProfile?.referralCode || createReferralCode(),
          friends: Array.isArray(parsed?.socialProfile?.friends) ? parsed.socialProfile.friends : [],
        },
        leaderboardRank: parsed.leaderboardRank || estimateLeaderboardRank(parsed.totalReps || 0),
        streak: computeStreak(parsed.dailyHistory || {}),
        // Session state never survives a reload
        workout: null,
        currentExercise: null,
        currentTarget: null,
        repsCompleted: 0,
        isExercising: false,
        manualLogOverride: false,
        showEquipmentSetup: false,
        showProgramBuilder: false,
        showLevelUp: false,
        showSummary: false,
        showCamera: false,
        showHowTo: false,
        showLegal: null,
      };
    }
  } catch { /* ignore */ }
  return initialState;
}

function saveState(state) {
  try {
    const {
      workout, currentExercise, currentTarget, isExercising, showCamera,
      showLevelUp, showSummary, showHowTo, showEquipmentSetup, showLegal, lastSet,
      showProgramBuilder, manualLogOverride,
      ...persistent
    } = state;
    localStorage.setItem(STORAGE_KEY, JSON.stringify(persistent));
  } catch { /* ignore */ }
}

/** Build a fresh workout session object from a program day. */
function buildWorkout(state, dayIndex) {
  const day = state.program?.days?.[dayIndex % (state.program?.days?.length || 1)];
  if (!day) return null;
  return {
    dayIndex,
    dayName: day.name,
    focus: day.focus,
    items: day.items.map((item) => {
      const rx = state.program?.custom
        ? getPrescription(item, { model: state.program.model, oneRMs: state.oneRMs, formProfile: state.formProfile })
        : null;
      return {
        exerciseId: item.exerciseId,
        pattern: item.pattern,
        sets: rx ? rx.sets : item.sets,
        prescription: rx, // { sets, repMin, repMax, targetReps, weightLb, pct } for custom programs
        results: [], // one entry per completed set: { reps, formScore, weightLb }
      };
    }),
    itemIndex: 0,
    startedAt: Date.now(),
  };
}

function targetForCurrent(state, exercise, workout) {
  const wItem = workout?.items?.[workout.itemIndex];
  if (state.program?.custom && wItem?.prescription) {
    return wItem.prescription.targetReps;
  }
  const lastResult = wItem?.results?.slice(-1)[0] || null;
  return computeTarget(exercise, {
    gender: state.gender,
    activityLevel: state.activityLevel,
    sessionsCompleted: state.sessionsCompleted,
    goal: state.userProfile.goal,
    model: state.userProfile.progressionModel,
    dayIndex: workout?.dayIndex || 0,
    formProfile: state.formProfile,
    lastCompletionRatio: lastResult && state.currentTarget
      ? lastResult.reps / state.currentTarget
      : null,
  });
}

function regenerate(state) {
  return generateProgram({
    goal: state.userProfile.goal,
    experience: state.userProfile.experience,
    daysPerWeek: state.userProfile.daysPerWeek,
    equipment: state.userEquipment,
    formProfile: state.formProfile,
  });
}

function reducer(state, action) {
  switch (action.type) {
    case 'COMPLETE_ONBOARDING': {
      const { gender, goal, experience, daysPerWeek, equipment } = action.payload || {};
      const expActivity = { beginner: 'beginner', intermediate: 'moderate', advanced: 'active' };
      const next = {
        ...state,
        onboardingComplete: true,
        gender: gender || 'male',
        activityLevel: expActivity[experience] || 'moderate',
        userProfile: {
          ...state.userProfile,
          goal: goal || 'muscle',
          experience: experience || 'intermediate',
          daysPerWeek: daysPerWeek || 3,
        },
        userEquipment: equipment || [],
      };
      return {
        ...next,
        program: regenerate(next),
        nextDayIndex: 0,
        showProgramBuilder: action.payload?.programMode === 'build',
      };
    }

    case 'ACCEPT_DISCLAIMER':
      return { ...state, disclaimerAccepted: true };

    case 'START_WORKOUT': {
      const dayIndex = action.payload?.dayIndex ?? state.nextDayIndex;
      const workout = buildWorkout(state, dayIndex);
      if (!workout) return state;
      const exercise = getExerciseById(workout.items[0].exerciseId);
      return {
        ...state,
        workout,
        currentExercise: exercise,
        currentTarget: targetForCurrent(state, exercise, workout),
        isExercising: true,
        showHowTo: true,
        showCamera: false,
        showSummary: false,
        repsCompleted: 0,
        manualLogOverride: false,
        formStatus: { level: 'green', message: 'Get ready...' },
      };
    }

    case 'DISMISS_HOW_TO':
      return { ...state, showHowTo: false, showCamera: true };

    // Form-check bypass for the rest of this workout
    case 'LOG_MANUALLY':
      return { ...state, manualLogOverride: true, showHowTo: false, showCamera: true };

    // One camera run = one set.
    case 'COMPLETE_EXERCISE': {
      if (!state.workout || !state.currentExercise) return state;
      const { reps = 0, holdTime = 0, formScore = 100, topNote = null, manual = false } = action.payload;
      const counted = state.currentExercise.type === 'hold' ? Math.floor(holdTime) : reps;
      const curItem = state.workout.items[state.workout.itemIndex];
      const weightLb = curItem?.prescription?.weightLb ?? null;

      // 1. Record the set (manual sets carry no form score)
      const items = state.workout.items.map((item, i) =>
        i === state.workout.itemIndex
          ? { ...item, results: [...item.results, { reps: counted, formScore: manual ? null : Math.round(formScore), weightLb }] }
          : item
      );
      const item = items[state.workout.itemIndex];
      const setNumber = item.results.length;
      const setsRemaining = item.sets - setNumber;
      const moreItems = state.workout.itemIndex < items.length - 1;
      const nextAction = setsRemaining > 0 ? 'next-set' : moreItems ? 'next-exercise' : 'workout-done';

      // 2. Form profile — the primary programming input.
      // Manual sets never touch the form profile (no camera = no form data).
      const formProfile = manual
        ? state.formProfile
        : updateFormProfile(state.formProfile, state.currentExercise.id, formScore);
      const oneRMs = weightLb
        ? updateEstimated1RM(state.oneRMs, state.currentExercise.id, weightLb, counted, manual ? 100 : formScore)
        : state.oneRMs;
      const adaptation = manual
        ? null
        : getAdaptation(state.currentExercise.id, formProfile, state.userEquipment, state.userProfile.experience);

      // 3. XP / totals / history (manual reps earn slightly less XP than verified clean reps)
      const xpGained = manual
        ? Math.round(counted * 8) || Math.round(holdTime * 2)
        : Math.round(counted * 10 * (formScore / 100)) || Math.round(holdTime * 2);
      const newXP = state.xp + xpGained;
      const leveledUp = getLevelForXP(newXP).level > getLevelForXP(state.xp).level;

      const today = new Date().toISOString().split('T')[0];
      const todayHistory = state.dailyHistory[today] || { reps: 0, sessions: 0, bestFormScore: 0 };
      const dailyHistory = {
        ...state.dailyHistory,
        [today]: {
          ...todayHistory,
          reps: todayHistory.reps + counted,
          sessions: todayHistory.sessions + (nextAction === 'workout-done' ? 1 : 0),
          bestFormScore: manual ? (todayHistory.bestFormScore || 0) : Math.max(todayHistory.bestFormScore || 0, Math.round(formScore)),
        },
      };

      const prevBest = state.exerciseBests?.[state.currentExercise.id] || 0;
      const isPersonalBest = counted > prevBest && counted > 0;
      const exerciseBests = { ...state.exerciseBests, [state.currentExercise.id]: Math.max(prevBest, counted) };

      const cleanReps = manual ? counted : Math.round(counted * (formScore / 100));

      return {
        ...state,
        workout: { ...state.workout, items },
        formProfile,
        oneRMs,
        isExercising: false,
        showCamera: false,
        showSummary: true,
        showLevelUp: leveledUp,
        repsCompleted: counted,
        totalReps: state.totalReps + counted,
        xp: newXP,
        sessionsCompleted: nextAction === 'workout-done' ? state.sessionsCompleted + 1 : state.sessionsCompleted,
        leaderboardRank: estimateLeaderboardRank(state.totalReps + counted),
        dailyHistory,
        streak: computeStreak(dailyHistory),
        exerciseBests,
        lastSet: {
          exercise: state.currentExercise.name,
          exerciseId: state.currentExercise.id,
          isHold: state.currentExercise.type === 'hold',
          setNumber,
          totalSets: item.sets,
          target: state.currentTarget,
          cleanReps,
          flaggedReps: counted - cleanReps,
          formScore: manual ? null : Math.round(formScore),
          manual,
          weightLb,
          personalBest: isPersonalBest,
          topNote,
          adaptation,
          nextAction,
          nextExerciseName: moreItems ? getExerciseById(items[state.workout.itemIndex + 1].exerciseId)?.name : null,
        },
      };
    }

    // Advance the session from the summary screen.
    case 'CONTINUE_WORKOUT': {
      if (!state.workout || !state.lastSet) return state;
      const { nextAction } = state.lastSet;

      if (nextAction === 'next-set') {
        return {
          ...state,
          showSummary: false,
          showCamera: true,
          isExercising: true,
          repsCompleted: 0,
          currentTarget: targetForCurrent(state, state.currentExercise, state.workout),
        };
      }

      if (nextAction === 'next-exercise') {
        const itemIndex = state.workout.itemIndex + 1;
        const workout = { ...state.workout, itemIndex };
        const exercise = getExerciseById(workout.items[itemIndex].exerciseId);
        return {
          ...state,
          workout,
          currentExercise: exercise,
          currentTarget: targetForCurrent(state, exercise, workout),
          showSummary: false,
          showHowTo: true,
          isExercising: true,
          repsCompleted: 0,
        };
      }

      // workout-done → adapt the program with fresh form + performance data
      const program = adaptProgram(
        state.program, state.formProfile, state.userEquipment, state.userProfile.experience,
        { dayIndex: state.workout.dayIndex, items: state.workout.items }
      );
      return {
        ...state,
        program,
        nextDayIndex: (state.workout.dayIndex + 1) % (state.program?.days?.length || 1),
        workout: null,
        currentExercise: null,
        currentTarget: null,
        showSummary: false,
        isExercising: false,
        repsCompleted: 0,
      };
    }

    // Bail out mid-workout (still keeps recorded sets/XP)
    case 'END_WORKOUT': {
      const program = adaptProgram(
        state.program, state.formProfile, state.userEquipment, state.userProfile.experience,
        state.workout ? { dayIndex: state.workout.dayIndex, items: state.workout.items } : null
      );
      return {
        ...state,
        program,
        workout: null,
        currentExercise: null,
        currentTarget: null,
        showSummary: false,
        showCamera: false,
        showHowTo: false,
        isExercising: false,
        repsCompleted: 0,
      };
    }

    // Swap the current exercise for an equipment-aware substitute
    case 'SUBSTITUTE_EXERCISE': {
      if (!state.workout || !state.currentExercise) return state;
      const sub = getSubstitute(
        state.currentExercise.id, state.userEquipment, state.userProfile.experience, state.formProfile
      );
      if (!sub) return state;
      const items = state.workout.items.map((it, i) =>
        i === state.workout.itemIndex ? { ...it, exerciseId: sub.id, results: [] } : it
      );
      const workout = { ...state.workout, items };
      return {
        ...state,
        workout,
        currentExercise: sub,
        currentTarget: targetForCurrent(state, sub, workout),
        repsCompleted: 0,
        formStatus: { level: 'green', message: `Switched to ${sub.name}` },
      };
    }

    // Switch by name (used by CameraScreen's switcher)
    case 'SWITCH_EXERCISE': {
      const target = exercises.find((e) => e.name === action.payload);
      if (!target) return state;
      const items = state.workout
        ? state.workout.items.map((it, i) =>
            i === state.workout.itemIndex ? { ...it, exerciseId: target.id, results: [] } : it
          )
        : null;
      const workout = state.workout ? { ...state.workout, items } : null;
      return {
        ...state,
        workout,
        currentExercise: target,
        currentTarget: targetForCurrent(state, target, workout),
        repsCompleted: 0,
        formStatus: { level: 'green', message: 'Switched — get ready' },
      };
    }

    case 'REGENERATE_PROGRAM':
      return { ...state, program: regenerate(state), nextDayIndex: 0 };

    case 'SET_PROGRESSION_MODEL': {
      const userProfile = { ...state.userProfile, progressionModel: action.payload };
      return { ...state, userProfile };
    }

    case 'SET_GOAL': {
      const next = { ...state, userProfile: { ...state.userProfile, goal: action.payload } };
      return { ...next, program: regenerate(next), nextDayIndex: 0 };
    }

    case 'SET_EQUIPMENT': {
      const next = { ...state, userEquipment: action.payload, showEquipmentSetup: false };
      return { ...next, program: regenerate(next), nextDayIndex: 0 };
    }

    case 'SHOW_EQUIPMENT_SETUP':
      return { ...state, showEquipmentSetup: true };

    case 'SHOW_PROGRAM_BUILDER':
      return { ...state, showProgramBuilder: true };

    case 'DISMISS_PROGRAM_BUILDER':
      return { ...state, showProgramBuilder: false };

    // Save a user-designed program from the builder
    case 'SAVE_PROGRAM': {
      const { days, model, oneRMs: builder1RMs } = action.payload || {};
      const program = buildCustomProgram(days || [], model || 'double', state.userProfile.goal);
      if (!program.days.length) return { ...state, showProgramBuilder: false };
      // Merge manual 1RM entries from the builder
      const oneRMs = { ...state.oneRMs };
      Object.entries(builder1RMs || {}).forEach(([id, manual]) => {
        if (manual) oneRMs[id] = { ...(oneRMs[id] || {}), manual };
      });
      return {
        ...state,
        program,
        oneRMs,
        userProfile: { ...state.userProfile, progressionModel: model || 'double', daysPerWeek: program.daysPerWeek },
        nextDayIndex: 0,
        showProgramBuilder: false,
      };
    }

    case 'SET_ONE_RM': {
      const { exerciseId, manualLb } = action.payload || {};
      if (!exerciseId) return state;
      return {
        ...state,
        oneRMs: {
          ...state.oneRMs,
          [exerciseId]: { ...(state.oneRMs[exerciseId] || {}), manual: manualLb || null },
        },
      };
    }

    case 'DISMISS_LEVEL_UP':
      return { ...state, showLevelUp: false };

    case 'DISMISS_SUMMARY':
      return { ...state, showSummary: false };

    case 'TOGGLE_SETTING': {
      const key = action.payload;
      let newValue;
      if (key === 'camera') {
        newValue = state.settings.camera === 'Front' ? 'Rear' : 'Front';
      } else if (key === 'units') {
        newValue = state.settings.units === 'kg' ? 'lb' : 'kg';
      } else {
        newValue = !state.settings[key];
      }
      return { ...state, settings: { ...state.settings, [key]: newValue } };
    }

    case 'TOGGLE_GENDER':
      return { ...state, gender: state.gender === 'male' ? 'female' : 'male' };

    case 'SHOW_LEGAL':
      return { ...state, showLegal: action.payload };

    case 'DISMISS_LEGAL':
      return { ...state, showLegal: null };

    case 'UPDATE_FORM_STATUS':
      return { ...state, formStatus: action.payload };

    case 'SET_DISPLAY_NAME': {
      const next = (action.payload || '').trim().slice(0, 20);
      if (!next) return state;
      return { ...state, socialProfile: { ...state.socialProfile, displayName: next } };
    }

    case 'ADD_FRIEND_CODE': {
      const code = normalizeCode(action.payload);
      const ownCode = normalizeCode(state.socialProfile.referralCode);
      const friends = (state.socialProfile.friends || []).map(normalizeCode);
      if (!code || code === ownCode) return state;
      if (friends.includes(code)) return state;
      return {
        ...state,
        socialProfile: { ...state.socialProfile, friends: [...friends, code].slice(0, 100) },
      };
    }

    case 'APPLY_REFERRAL_CODE': {
      const code = (action.payload || '').trim().toUpperCase();
      if (!code || code === state.socialProfile.referralCode || state.socialProfile.referredBy) return state;
      return { ...state, socialProfile: { ...state.socialProfile, referredBy: code } };
    }

    default:
      return state;
  }
}

export const AppContext = createContext();

export function AppProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, null, loadState);

  useEffect(() => {
    saveState(state);
  }, [state]);

  // Best-effort social sync for live leaderboard backend (if configured).
  useEffect(() => {
    if (!isSocialBackendConfigured()) return;
    let cancelled = false;
    const timer = setTimeout(async () => {
      try {
        if (!cancelled) await syncSocialProfile(state);
      } catch {
        // Keep app fully functional if social backend is unavailable.
      }
    }, 300);
    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
  }, [
    state.xp,
    state.totalReps,
    state.streak,
    state.socialProfile?.displayName,
    state.socialProfile?.referralCode,
    state.socialProfile?.referredBy,
    JSON.stringify(state.socialProfile?.friends || []),
  ]);

  // Safety net: if a persisted profile exists without a program, generate one.
  useEffect(() => {
    if (state.onboardingComplete && !state.program) {
      dispatch({ type: 'REGENERATE_PROGRAM' });
    }
  }, [state.onboardingComplete, state.program]);

  return (
    <AppContext.Provider value={{ state, dispatch }}>
      {children}
    </AppContext.Provider>
  );
}
